server:
    port: 8081
    servlet:
        context-path: /api

primary:
    datasource:
        data: classpath:scripts.sql
        tomcat:
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: postgres
            url: jdbc:postgresql://localhost:5432/testdb

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                format_sql: true
                generate_statistics: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: postgresql
